name: Run Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v1

    - name: Run Tests
      run: dotnet test NameOn.Core.Test/NameOn.Core.Test.csproj
